---
title: "Métodos em Análise Multivariada (ME731)"
subtitle: "Distribuição Normal Multivariada"
session: "03"
author: 'Prof. Carlos Trucíos <br><a href="http://ctruciosm.github.io"> <i class="fa fa-desktop fa-fw"></i>&nbsp; ctruciosm.github.io</a><br> <a href="mailto:ctrucios@unicamp.br"><i class="fa fa-paper-plane fa-fw"></i>&nbsp; ctrucios@unicamp.br</a><br>'
institute: "Instituto de Matemática, Estatística e Computação Científica, </br> Universidade Estadual de Campinas"
output:
  xaringan::moon_reader:
    css: "xaringan-themer.css"
    lib_dir: libs
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: false
    includes:
      in_header: header.html
---
layout: true

<a class="footer-link" href="http://ctruciosm.github.io">ctruciosm.github.io &mdash; Carlos Trucíos (IMECC/UNICAMP)</a>


<style type="text/css">
.remark-slide-content {
    font-size: 26px;
    padding: 1em 3.5em 1em 3.5em;
}
</style>


---


```{r xaringanExtra, echo=FALSE}
xaringanExtra::use_xaringan_extra(c("tile_view", "tachyons", "scribble", "panelset", "freezeframe", "clipboard"))
xaringanExtra::use_extra_styles(
  hover_code_line = TRUE,         
  mute_unhighlighted_code = FALSE
)
xaringanExtra::use_logo(
  image_url = "imagens/unicamp.png",
  width = "100px",
  height = "150px")
```


```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_xaringan()
#style_duo_accent(link_color = "#8A0808",
#                 blockquote_left_border_color = "red")
```




#### Distribuição Normal Multivariada


.panelset[
.panel[.panel-name[Correlação 0]

```{r, echo = FALSE, message=FALSE, warning=FALSE, fig.height = 5.5, fig.width= 15}
library(dplyr)
library(plotly)
x <- seq(-4, 4, length.out = 40)
y <- seq(-4, 4, length.out = 40)
mvals <- expand.grid(x,y)
mu <- c(0,0)

Sigma <- matrix(c(1,0,0,1), 2)
mvds <- mvtnorm::dmvnorm(x = mvals, mean = mu, sigma = Sigma)
matrix_mvds <-  matrix(mvds, nrow = 40)
plot_ly(x = x, y = y, z = matrix_mvds) %>% add_surface(
  contours = list(
    z = list(
      show = TRUE,
      usecolormap = TRUE,
      highlightcolor = "#ff0000",
      project = list(z = TRUE)
      )
    )
  ) %>% layout(
    scene = list(
      camera = list(
        eye = list(x = 1.87, y = 0.88, z = -0.64)
        )
      )
  )
```

]

.panel[.panel-name[Correlação 0.75]

```{r, echo = FALSE, message=FALSE, warning=FALSE, fig.height = 5.5, fig.width= 15}
Sigma <- matrix(c(1,0.75,0.75,1), 2)
mvds <- mvtnorm::dmvnorm(x = mvals, mean = mu, sigma = Sigma)
matrix_mvds <-  matrix(mvds, nrow = 40)
plot_ly(x = x, y = y, z = matrix_mvds) %>% add_surface(
  contours = list(
    z = list(
      show = TRUE,
      usecolormap = TRUE,
      highlightcolor = "#ff0000",
      project = list(z = TRUE)
      )
    )
  ) %>% layout(
    scene = list(
      camera = list(
        eye = list(x = 1.87, y = 0.88, z = -0.64)
        )
      )
  )
```

]

.panel[.panel-name[Correlação -0.9]

```{r, echo = FALSE, message=FALSE, warning=FALSE, fig.height = 5.5, fig.width= 15}
Sigma <- matrix(c(1,-0.9,-0.9,1), 2)
mvds <- mvtnorm::dmvnorm(x = mvals, mean = mu, sigma = Sigma)
matrix_mvds <-  matrix(mvds, nrow = 40)
plot_ly(x = x, y = y, z = matrix_mvds) %>% add_surface(
  contours = list(
    z = list(
      show = TRUE,
      usecolormap = TRUE,
      highlightcolor = "#ff0000",
      project = list(z = TRUE)
      )
    )
  ) %>% layout(
    scene = list(
      camera = list(
        eye = list(x = 1.87, y = 0.88, z = -0.64)
        )
      )
  )
```
]]

